services:
  sparseindex-service:
    build:
      context: .
    volumes:
      - ./app:/srv/app
      - ../add-ai-core:/add-ai-core
      - bm25_cache:/data/bm25_cache
    command: >
      sh -c "pip install -e /add-ai-core &&
             uvicorn app.main:app --host 0.0.0.0 --port 8005 --reload"
